servername = "velocity" # used to send and receive packets
enable_server_connect_listener = true # allows plugins on paper/bukkit to make connection requests to other servers
[socket_pool]

[socket_pool.assign] # socket port assigned on this instance, address is localhost
start = 4000
end = 5000

[socket_pool.search] # socket port to bind with other servers, address is localhost
start = 4000
end = 5000